

name: Develop

on: 
  pull_request: 
    branches:
      - develop
    

jobs:

  TesteUnitario:
    runs-on: ubuntu-latest
    
    container:
      image: pedrohsalmeida/nimbus-backend:latest
      options: --entrypoint /bin/sh
      env:
        PORT: ${{ secrets.PORT }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        DB_URL_MONGO_BACK: ${{ secrets.DB_URL_MONGO_BACK }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Instalando dempendencias
        run: npm install
    
      - name: rodando testes
        id: test
        run: npm run test:unit



  AceitaRecusaPR:
    runs-on: ubuntu-latest
    needs: TesteUnitario

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Aprovando pull_request se os testes passarem
        id: aprovado
        uses: juliangruber/approve-pull-request-action@v2 
        with:
            github-token: ${{ secrets.ADM_TOKEN }}
            number: ${{ github.event.pull_request.number }}
  
      - name: Merge Pull Request
        if: steps.aprovado.outcome == 'success'
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.ADM_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          method: squash
  
      - run: echo "HEAD:${{github.event.pull_request.head.repo.name}}, BASE:${{github.event.pull_request.base.repo.name}}"

  PushDokerHub:
    runs-on: ubuntu-latest

    needs: AceitaRecusaPR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar Docker para autenticação
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Construir a imagem Docker
        run: |
          # Usando o número do pull request como parte da tag
          docker build -t pedrohsalmeida/nimbus-backend:Dev-0.${{ github.event.number }} .
          docker tag pedrohsalmeida/nimbus-backend:Dev-0.${{ github.event.number }} pedrohsalmeida/nimbus-backend:latest

      - name: Push da imagem para o Docker Hub
        run: |
          docker push pedrohsalmeida/nimbus-backend:Dev-0.${{ github.event.number }}
          docker push pedrohsalmeida/nimbus-backend:latest


