
name: Teste Completo

on: 
  pull_request: 
    branches:
      - release


jobs:
    TesteUnitario:
        runs-on: ubuntu-latest

        container:
          image: pedrohsalmeida/nimbus-backend:Dev-latest
          options: --entrypoint /bin/sh # Usa '/bin/sh' para garantir que os comandos 'run' funcionem
          env:
            PORT: ${{ secrets.PORT }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            DB_URL_MONGO_BACK: ${{ secrets.DB_URL_MONGO_BACK }}


        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Instalando dempendencias
          run: npm install
          
        - name: rodando testes
          id: test
          run: npm run test:unit

    CriandoImagemTeste:
      runs-on: ubuntu-latest
      needs: TesteUnitario
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Instalando dempendencias
          run: npm install

        - name: Instalar Docker Compose
          run: sudo apt-get install docker-compose


        - name: Construir Imagem Docker
          run: docker-compose build

        - name: Configurar Docker para autenticação
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        
        - name: Construir a imagem Docker
          run: |
            # Usando o número do pull request como parte da tag
            docker build -t pedrohsalmeida/nimbus-backend:integracao .

        - name: push imagem
          run: docker push pedrohsalmeida/nimbus-backend:integracao


    TesteIntegracao:
      needs: CriandoImagemTeste
      runs-on: ubuntu-latest

      services:
        db:
          image: postgres
          env:
            POSTGRES_USER: ${{secrets.POSTGRES_USER}}
            POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
            POSTGRES_DB: ${{ secrets.DB_NAME_TEST }}
          ports:
            - 5432:5432

        backend:
          image: pedrohsalmeida/nimbus-backend:integracao
          env:
            PORT: ${{secrets.PORT}}
            JWT_SECRET: dsvsvdsv
            DB_URL_MONGO_BACK: ${{secrets.DB_URL_MONGO_BACK}}
            DB_NAME: ${{secrets.DB_NAME_TEST}}
            DB_HOST: db
            DB_USER: ${{secrets.DB_USER}}
            DB_PORT: ${{secrets.DB_PORT}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            DB_NAME_TEST: ${{secrets.DB_NAME_TEST}}
            NODE_ENV: test
          ports:
            - 8000:8000

        frontend:
          image: pedrohsalmeida/nimbus-frontend:Dev-latest
          env:
            NEXT_PUBLIC_BACK_HOST: backend
          ports:
            - 3000:3000
          
      steps:

        - name: Checkout code
          uses: actions/checkout@v3
          with:
            repository: Equipe-Nimbus/API-DSM4-Frontend
            ref: develop
      

        - name: List Docker images
          run: | 
            docker image ls -a
            docker ps
        
        - uses: cypress-io/github-action@v6
          with:
            browser: chrome
          env:
            CYPRESS_host: http://localhost:3000

    
    AceitaRecusaPR:
      runs-on: ubuntu-latest
      needs: TesteIntegracao
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Aprovando pull_request se os testes passarem
          uses: juliangruber/approve-pull-request-action@v2 
          with:
              github-token: ${{ secrets.ADM_TOKEN }}
              number: ${{ github.event.pull_request.number }}

        - name: Merge Pull Request
          uses: juliangruber/merge-pull-request-action@v1
          with:
            github-token: ${{ secrets.ADM_TOKEN }}
            number: ${{ github.event.pull_request.number }}
            method: squash


        - run: echo "HEAD:${{github.event.pull_request.head.repo.name}}, BASE:${{github.event.pull_request.base.repo.name}}"


    PushDokerHub:
      runs-on: ubuntu-latest


      needs: AceitaRecusaPR

      steps:
        - name: Checkout code
          uses: actions/checkout@v3


        - name: Configurar Docker para autenticação
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}


        - name: Construir a imagem Docker
          run: |
            # Usando o número do pull request como parte da tag
            docker build -t pedrohsalmeida/nimbus-backend:Rel-0.${{ github.event.number }} .
            docker tag pedrohsalmeida/nimbus-backend:Rel-0.${{ github.event.number }} pedrohsalmeida/nimbus-backend:Rel-latest
    
    
        - name: Push da imagem para o Docker Hub
          run: |
            docker push pedrohsalmeida/nimbus-backend:Rel-0.${{ github.event.number }}
            docker push pedrohsalmeida/nimbus-backend:Rel-latest
    
    AvisaResultado:
      runs-on: ubuntu-latest

      needs: 
        - TesteIntegracao
        - AceitaRecusaPR
        - PushDokerHub
        - TesteUnitario
        - CriandoImagemTeste
      if: always()

      steps:

        - run: echo AceitaRecusaPR ${{ needs.AceitaRecusaPR.result}} 
        - run: echo PushDokerHub ${{ needs.PushDokerHub.result}}
        - run: echo TesteIntegracao ${{ needs.PushDokerHub.result}}

        - name: Notificacao de sucesso
          if: ${{ needs.TesteUnitario.result == 'success' && needs.CriandoImagemTeste.result == 'success' && needs.TesteIntegracao.result == 'success' && needs.AceitaRecusaPR.result == 'success' && needs.PushDokerHub.result == 'success' }}
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          uses: Ilshidur/action-discord@master
          with:
            args: |
              Pull request de ${{github.event.pull_request.user.login}} foi um SUCESSO 
              Da ${{ github.event.pull_request.head.ref }} para ${{ github.event.pull_request.base.ref }}
              PR(${{ github.event.pull_request.number }}): ${{ github.event.pull_request.title }}
              ${{ github.event.pull_request.html_url }}



        - name: Notificacao de falha
          if: ${{ needs.TesteUnitario.result != 'success' || needs.CriandoImagemTeste.result != 'success' || needs.TesteIntegracao.result != 'success' || needs.AceitaRecusaPR.result != 'success' || needs.PushDokerHub.result != 'success' }}
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          uses: Ilshidur/action-discord@master
          with:
            args: |
              Pull request de ${{github.event.pull_request.user.login}} FALHOU
              Da ${{ github.event.pull_request.head.ref }} para ${{ github.event.pull_request.base.ref }}
              PR(${{ github.event.pull_request.number }}): ${{ github.event.pull_request.title }}
              ${{ github.event.pull_request.html_url }}